version: '3.7'
services:
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    environment:
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - es_redis:/data

volumes:
  es_redis:
    driver: local
